### PR TITLE
Let logging format messages on demand

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by JonnyJD** [comment]
Would you please elaborate a bit on the problem and your solution? I only see a syntax change from what is suggested in Python 3 and what is naturally used in Python 2.

**Comment by scop** [comment]
I don't think you're reading the change quite right. This is not about formatting style. With this change, log messages that don't end up being logged don't need to be formatted at all. (Probably next to non-issue with isrcsubmit, but...)

**Comment by JonnyJD** [comment]
Oh, so you want to optimize string handling for short strings in an interactive script? :-D

I never considered that difference, because that is not at all relevant for the performance of any of my scripts (including isrcsubmit).

I might consider it for "style reasons" though. That way it is already a good example if a snipped like that will ever become "critical".

**Comment by JonnyJD** [comment]
thanks

**Pull request merged**
